# Generated by Django 5.2.6 on 2025-09-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction_listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField()),
                ("start_bid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField()),
                ("url", models.URLField()),
            ],
        ),
    ]
