# Generated by Django 5.2.6 on 2025-10-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="date_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="seller",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="auction_listing",
            name="category",
            field=models.CharField(max_length=64),
        ),
    ]
