# Generated by Django 5.2.6 on 2025-10-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auction_listing_date_time_auction_listing_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="date_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="auction_listing",
            name="seller",
            field=models.CharField(),
        ),
    ]
