# Generated by Django 5.2.6 on 2025-10-02 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wquery",
                to="auctions.auction_listing",
            ),
        ),
    ]
