# Generated by Django 5.2.6 on 2025-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_watchlist_listing_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="highest_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
