# Generated by Django 5.2.6 on 2025-10-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_auction_listing_highest_bid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Closed_Auction_listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField()),
                ("start_bid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("highest_bid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=64)),
                ("url", models.URLField()),
                ("seller", models.CharField()),
                ("date_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Bids",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "listing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auctions.auction_listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "listing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auctions.auction_listing",
                    ),
                ),
            ],
        ),
    ]
