# Generated by Django 5.2.6 on 2025-10-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_closed_auction_listing_bids_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bids",
            new_name="Bid",
        ),
    ]
