# Generated by Django 5.2.6 on 2025-10-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_rename_bids_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="user",
            field=models.CharField(null=True),
        ),
    ]
