# Generated by Django 5.2.6 on 2025-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_bid_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.CharField(),
        ),
    ]
