# Generated by Django 5.2.6 on 2025-10-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_bid_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="closed_auction_listing",
            name="winner",
            field=models.CharField(null=True),
        ),
    ]
