# Generated by Django 5.2.6 on 2025-10-06 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_closed_auction_listing_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="activity",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="winner",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="listing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wquery",
                to="auctions.auction_listing",
            ),
        ),
    ]
