# Generated by Django 5.2.6 on 2025-10-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_auction_listing_activity_auction_listing_winner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="category",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="description",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="highest_bid",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="start_bid",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="title",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="url",
        ),
        migrations.RemoveField(
            model_name="closed_auction_listing",
            name="winner",
        ),
    ]
