# Generated by Django 5.2.7 on 2025-10-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_remove_closed_auction_listing_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Closed_Auction_listing",
        ),
    ]
