# Generated by Django 5.2.7 on 2025-10-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_delete_closed_auction_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="user",
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
