# Generated by Django 5.2.7 on 2025-10-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_comments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="listing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auction_listing",
            ),
        ),
    ]
