# Generated by Django 5.2.7 on 2025-10-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_comments_listing_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
