# Generated by Django 5.2.7 on 2025-10-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_alter_watchlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fashion", "Fashion"),
                    ("Home", "Home"),
                    ("Toys", "Toys"),
                    ("Electronics", "Electronics"),
                    ("Furniture", "Furniture"),
                ]
            ),
        ),
    ]
