# Generated by Django 5.2.7 on 2025-10-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_alter_auction_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="winner",
            field=models.CharField(blank=True, null=True),
        ),
    ]
