# Generated by Django 5.2.7 on 2025-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0022_alter_auction_listing_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Fashion", "Fashion"),
                    ("Home", "Home"),
                    ("Toys", "Toys"),
                    ("Electronics", "Electronics"),
                    ("Furniture", "Furniture"),
                ]
            ),
        ),
    ]
