# Generated by Django 5.2.7 on 2025-12-27 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "network",
            "0002_remove_post_username_post_user_alter_user_followers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
